### ISSUE TITLE
Galacticraft crash

### ISSUE THREAD

**Issue by hipy** [LepkoQQ/EasyCrafting#21]
Hi,

It seems like there is an incompatibility with galacticraft

Error log:
http://pastebin.com/nEDDMHq5

**Comment by hipy** [comment]
I found a fix here, I can't implement it.. can someone else fix it? 

https://github.com/LepkoQQ/EasyCrafting/blob/master/src/net/lepko/easycrafting/helpers/RecipeHelper.java#L240

**Comment by agaricusb** [comment]
Seeing this too with mods/EasyCrafting-1.1.5.jar + coremods/Galacticraft-1.5.1-a0.1.34.177.jar. The crash occurs when clicking an item in the Easy Crafting table to craft it:

> java.lang.ClassCastException: net.minecraft.entity.player.InventoryPlayer cannot be cast to micdoodle8.mods.galacticraft.core.inventory.GCCoreInventoryPlayer
>        at micdoodle8.mods.galacticraft.core.inventory.GCCoreInventoryPlayer.func_70455_b(GCCoreInventoryPlayer.java:366)
>        at net.lepko.easycrafting.helpers.RecipeHelper.canCraft(RecipeHelper.java:240)

due to Galacticraft (coremod) replacing the player inventory with its own class (GCCoreInventoryPlayer, for an expanded player inventory size), so inventory.copyInventory() fails with a CCE.

**Comment by hipy** [comment]
I never programmed for mods before, but is it not possible to request the players inventory size?

**Comment by LepkoQQ** [comment]
I just tried to figure out this issue earlier today and saw what happens, I'm thinking of replacing temp inventories with a List. Will fix as soon as I get the chance.

**Comment by LepkoQQ** [comment]
Fixed.
